services:
  web-server: # Define un servicio llamado "web-server"
    build: # Define cómo se va a construir la imagen del contenedor
      context: . # El contexto de construcción es el directorio actual
      dockerfile: Dockerfile # Especifica el archivo Dockerfile a utilizar para construir la imagen
    volumes:
     - .:/app
    ports:
     - '80:80'
